---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# `dia` package

<!-- badges: start -->
<!-- badges: end -->

The `dia` package implements the Development Impacts Analysis (DIA) model described
in Fullman et al. (in press) Ecosphere. The DIA quantifies potential
impacts of future development while accounting for uncertainty in development
location. This is done through simulation of development under different management
scenarios with quantification of the resulting impacts to species.

The workhorse of the `dia` package is the `dia` function. For an example of its use
please see the function documentation.

## Installation

To install the latest version of `dia` from [GitHub](https://github.com/):

``` r
# install.packages("devtools")
devtools::install_github("tfullman/dia")
```

## References
Fullman TJ, Sullender BK, Cameron MD, Joly K. in press. Simulation modeling
accounts for uncertainty while quantifying ecological effects of development
alternatives. Ecosphere.



